### ISSUE TITLE
wrapper fails for simple testprogram

### ISSUE THREAD

**Issue by smatkovi** [mwallerb/fsource#2]
the log is actually the f90-program. sebastian@debian:~/ps/nms2018$ ~/.local/bin/fsource wrap u06a.f90 
/home/sebastian/.local/lib/python2.7/site-packages/fsource/analyzer.py:156: UserWarning: CANNOT IMBUE <fsource.analyzer.CompilationUnit object at 0x7f9404b7bf90> WITH program_decl
  warnings.warn("CANNOT IMBUE %s WITH %s" % (parent, self.ast[0]))
/home/sebastian/.local/lib/python2.7/site-packages/fsource/analyzer.py:159: UserWarning: CANNOT RESOLVE program_decl
  warnings.warn("CANNOT RESOLVE %s" % self.ast[0])
Traceback (most recent call last):
  File "/home/sebastian/.local/bin/fsource", line 10, in <module>
    sys.exit(main())
  File "/home/sebastian/.local/lib/python2.7/site-packages/fsource/_cli.py", line 234, in main
    cmd_wrap(args)
  File "/home/sebastian/.local/lib/python2.7/site-packages/fsource/_cli.py", line 214, in cmd_wrap
    print (asr.cdecl().get())
  File "/home/sebastian/.local/lib/python2.7/site-packages/fsource/analyzer.py", line 189, in cdecl
    return CWrapper.union(self.children)
  File "/home/sebastian/.local/lib/python2.7/site-packages/fsource/analyzer.py", line 67, in union
    wraps = tuple(elem.cdecl() for elem in elems)
  File "/home/sebastian/.local/lib/python2.7/site-packages/fsource/analyzer.py", line 67, in <genexpr>
    wraps = tuple(elem.cdecl() for elem in elems)
AttributeError: 'Ignored' object has no attribute 'cdecl'
[u06a.log](https://github.com/mwallerb/fsource/files/4731288/u06a.log)

**Comment by mwallerb** [comment]
Thanks for the bug report!

Fortran programs cannot really be wrapped with C, since they're not callable (similar to the `main()` function).

However, the error message is less than helpful.  This should be fixed in the current master. For me it now prints:
```
/*
 * Wrapping failures:
 *   - program_decl: unable to wrap (ignored)
 */
```
